### ISSUE TITLE
GSM8k policy hf weigh problem

### ISSUE THREAD

**Issue by TnTWoW** [waterhorse1/LLM_Tree_Search#12]
Hello, thanks for interesting work.

I wonder if there is a problem with the model weights you uploaded (GSM8k policy hf)

I followed your instructions to use the strategy function to generate the problem-solving steps, but I only got a bunch of garbled code as shown below. 
<img width="1817" alt="4a992bf811de0a52fc607b40dc7975f" src="https://github.com/user-attachments/assets/c4e04011-0bc1-4adc-b77e-fcbb35cf2732">

I rechecked the model structure and found that the model did not even have an output head. I wonder what happened
<img width="794" alt="e0e762c5c9aad07aaf3738a7361e20b" src="https://github.com/user-attachments/assets/06cf5155-3170-4fd2-8b62-292a2bf381cb">

Thanks for your attention!

**Comment by waterhorse1** [comment]
@ziyuwan Ziyu can you have a look over this issue?

**Comment by ziyuwan** [comment]
Hi @TnTWoW
Can you provide some extra information for us to reproduce your error?
- your running environment, e.g. version of transformers, pytorch, ctranlated2 and etc.
- the certain prompt/question input here?

**Comment by TnTWoW** [comment]
Thanks for attention! I download gsm8k [policy weight](https://huggingface.co/OhCherryFire/llama2-7b-gsm8k-policy-hf) provided by you. Then  I use a question in gsm8k as prompt input and  find it can not generate any useful output (fig 1), and I check the model structure find the polkicy model has no output head (fig 2). My understanding of the policy network is a language model that can generate tokens, not an encoder. I want to know if my understanding is distorted or if the policy network you provided is wrong.

**Comment by ziyuwan** [comment]
<img width="855" alt="image" src="https://github.com/user-attachments/assets/b43b720a-c023-46f3-a1d4-f10913738de0" />
Sorry I cannot reproduce your error.
Do you consider share a minimal scripts/code for reproduction?

**Comment by TnTWoW** [comment]
I noticed that you loaded it from local.
Below is my code
```python
tokenizer= AutoTokenizer.from_pretrained('OhCherryFire/llama2-7b-gsm8k-policy-hf')
model = AutoModel.from_pretrained('OhCherryFire/llama2-7b-gsm8k-policy-hf').cuda()
>>> model
LlamaModel(
  (embed_tokens): Embedding(32001, 4096, padding_idx=0)
  (layers): ModuleList(
    (0-31): 32 x LlamaDecoderLayer(
      (self_attn): LlamaAttention(
        (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (mlp): LlamaMLP(
        (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
        (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
        (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
        (act_fn): SiLUActivation()
      )
      (input_layernorm): LlamaRMSNorm()
      (post_attention_layernorm): LlamaRMSNorm()
    )
  )
  (norm): LlamaRMSNorm()
)
```

**Comment by ziyuwan** [comment]
maybe you should not use `AutoModel`, you should use `AutoModelForCausalLM` instead. Is that right?

**Comment by TnTWoW** [comment]
You are right. My test srcript passed. I wrote this test script becasue of it happens in generating the policy. The policy network generates a mess of responses just like the test script, as shown in the following two figures: 

![image](https://github.com/user-attachments/assets/94b1e234-f197-49b7-bbd3-d39ba032189e)
![image](https://github.com/user-attachments/assets/1d4a706a-e112-4ef8-b72a-da172f059352)

I converted the policy network to ct2 according to the readme. However, I found that the command reported an error.

```python
ct2-transformers-converter --model {your huggingface model path} --quantization bfloat16 --output_dir {your ct2_cache target path}
# We use bfloat 16 for LLaMA model and float32 for GPT2 model
```

 It not support cuda11 and report error
 
```error
libcublas.so.11 is not found
```
so I used ct4 (https://github.com/OpenNMT/CTranslate2/issues/1250#issuecomment-1946131986) convert the policy model to C++. I guess maybe something wrong with ct4. Do you have code that uses HF directly for inference?

**Comment by waterhorse1** [comment]
Either you can reach out ct2 lib for the solution, or you can refer to huggingface doc on how to do the inference with transformers.

https://huggingface.co/docs/transformers/v4.47.1/en/main_classes/text_generation#transformers.GenerationMixin.generate
