### ISSUE TITLE
The trained model weights

### ISSUE THREAD

**Issue by Bo396543018** [waterhorse1/LLM_Tree_Search#2]
Hi, Thank you for great work. I want to test tsllm on gsm8k. Can I use your trained sft and critic model?

**Comment by waterhorse1** [comment]
Thank you for your interest. We are working on it and once we upload the model to huggingface I will notify you.

**Comment by Bo396543018** [comment]
Okay, thank you for your quick reply.

**Comment by liuchaofei** [comment]
> Hi, Thank you for great work. I want to test tsllm on gsm8k. Can I use your trained sft and critic model?

+1
